- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure NGINX
  copy:
    src: yii.conf
    dest: /etc/nginx/conf.d/yii.conf

- name: Restart NGINX
  systemd:
    name: nginx
    state: restarted
